#
#
version: '3.1'
#
services:
#
  inventory-service:
    image: brijeshdhaker/inventory-service:0.0.1-SNAPSHOT
    container_name: inventory-service
    ports:
      - 8091:8091

#
  payment-service:
    image: brijeshdhaker/payment-service:0.0.1-SNAPSHOT
    container_name: payment-service
    ports:
      - 8092:8092

#
  order-service:
    image: brijeshdhaker/order-service:0.0.1-SNAPSHOT
    container_name: order-service
    ports:
      - 8090:8090

#
  orchestrator-service:
    image: brijeshdhaker/orchestrator-service:0.0.1-SNAPSHOT
    container_name: orchestrator-service
    depends_on:
      - inventory-service
      - payment-service
    links:
      - inventory-service
      - payment-service
    ports:
      - 8093:8093

#
#networks:
#  default:
#    external:
#      name: bridge  
#  backend:
#    driver: bridge
# 