## YAML Template.
---
server:
  port: 8091
spring:
  application:
    name: payment-service
#    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  
    hibernate:
      ddl-auto: update
      use-new-id-gnerator-mappings: false
    properties:
      hibernate:
        show-sql: true
        use-sql-comments: true
        format-sql: true
        type: info
  datasource:
    name: INVENTORY
    username: sa
    password:
    driverClassName: org.h2.Driver  
    url: jdbc:h2:mem:INVENTORY
#    url: jdbc:h2:file:D:/apps/hostpath/databases/INVENTORY;AUTO_SERVER=true;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
#
  liquibase:
    enabled: false

#
---
#
# docker profile
#
---
#
spring:
  profiles: local
#
---

#
# docker profile
#
---
#
spring:
  profiles: docker  